name: send-to-website

on: push

jobs:
    compile-send:
        name: Compile and send CV to mjsobrep.com
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  path: main
            - uses: xu-cheng/latex-action@v2
              with:
                  root_file: MichaelSobrepera.tex
                  working_directory: main
            - uses: actions/checkout@v2
              with:
                  repository: mjsobrep/mjsobrep.github.io
                  path: website
                  ref: deploy
            - run: |
                rm website/otherFiles/MichaelSobrepera.pdf
                cp main/MichaelSobrepera.pdf website/otherFiles/MichaelSobrepera.pdf
            - name: setup git config
              run: |
                cd website
                git config user.name "GitHub Actions Bot"
                git config user.email "<>"
            - name: commit
              run: |
                cd website
                git add otherFiles/MichaelSobrepera.pdf
                git commit -m "new CV/Resume commit"
                git push origin develop
